#!/usr/bin/env bash

TERMINUS_DOES_MULTIDEV_EXIST()
{
    PANTHEON_MULTIDEV_LIST="$(terminus multidev:list -n ${TERMINUS_SITE} --format=list --field=Name)"

    while read -r multiDev; do
        if [[ "${multiDev}" == "$1" ]]
        then
            return 0;
        fi
    done <<< "$PANTHEON_MULTIDEV_LIST"

    return 1;
}

MULTIDEV_PREFIX=$( echo $CI_ENVIRONMENT_SLUG | cut -c -11 )
if ! TERMINUS_DOES_MULTIDEV_EXIST ${MULTIDEV_PREFIX}
then
    terminus multidev:create $TERMINUS_SITE.live $MULTIDEV_PREFIX -n -y
else 
    terminus env:clone-content $TERMINUS_SITE.live $MULTIDEV_PREFIX -n -y
    terminus build-env:push-code $TERMINUS_SITE.$MULTIDEV_PREFIX -n -y
fi